title: Droite.com
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.ico"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: tunhe38@gmail.com
github_username: Right202209  
# twitter_username: twitter
# instagram_username: instagram
# linkedin_username: linkedin
#facebook_username: facebook

# External API
giscus_repo:
giscus_repoId:
giscus_category:
giscus_categoryId:
goatcounter_code:
google_analytics:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
