title: Droite.com
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.ico"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: tunhe38@gmail.com
github_username: Right202209  
# twitter_username: twitter
# instagram_username: instagram
# linkedin_username: linkedin
#facebook_username: facebook

# External API
giscus_repo: "Droite7/Droite7.github.io"
giscus_repoId: "R_kgDOKdPpzQ"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOKdPpzc4CdA2y"
goatcounter_code:
google_analytics:


# # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                 #
#   Not recommended to touch the materials below  #
#                                                 #
#    Any changes may contribute to malfunction    #
#                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Build settings
theme: jekyll-theme-satellite

exclude:
  - _posts

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
